controllers/SiteController.php
<?php
namespace app\controllers;
use app\models\News;
use app\models\UserInfo;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\components\Access;
use yii\web\UploadedFile;
use app\models\UploadForm;
use yii\web\User;
class SiteController extends Controller
{
	private $salt = 'k5Go3Z0ib1RefT4u';
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}
	public function actionLogin()
	{
		if (!\Yii::$app->user->isGuest)
		{
			return $this->goHome();
		}
		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()))
		{
			$model->password = md5($model->password . $this->salt);
			if($model->login())
			{
				return $this->goBack();
			}
			$model->password = '';
		}
		return $this->render('login', ['model' => $model,]);
	}
	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}
	//
	public function actionIndex()
	{
		$news = News::GetAllNews_dataProvider();
		$bind = News::GetAllBindNews();
		return $this->render('index', ['news' => $news, 'bind' => $bind]);
	}
	public function actionGames()
	{
		return $this->render('games');
	}
	public function actionMarathon()
	{
		return $this->render('marathon');
	}
	public function actionRegistration()
	{
		if (!Yii::$app->user->isGuest)
		{
			return $this->goHome();
		}
		$model = new \app\models\User();
		if ($model->load(Yii::$app->request->post()))
		{
			$password = $model->password;
			
			$model->password = md5($model->password . $this->salt);
			
			$model->role = 'User';
			$model->save();
			$userinfo = new UserInfo();
			$userinfo->user_id = $model->id;
			$userinfo->save();
			return $this->render('registrationok', ['username' => $model->username, 'password' => $password]);
		}
		return $this->render('registration', ['model' => $model]);
	}
	public function actionProfile_view($id)
	{
		$model = UserInfo::GetUserInfo($id);
		if(!Access::ChekIs($model))
		{
			return $this->goHome();
		}
		return $this->render('profile_view', ['model' => $model]);
	}
	public function actionProfile()
	{
		if (Yii::$app->user->isGuest)
		{
			return $this->goHome();
		}
		$id = Access::GetUserId();
		$model = UserInfo::GetUserInfo($id);
		$upload = new UploadForm();
		if (!Access::ChekIs($model))
		{
			return $this->goHome();
		}
		if ($model->load(Yii::$app->request->post()))
		{
			$avatar = UploadedFile::getInstance($upload, 'file');
			if ($avatar && $upload->validate())
			{
				$allowtypes = ['jpeg', 'png', 'jpg', 'gif'];
				$curtype = $avatar->extension;
				$curtype = strtolower($curtype);
				if (in_array($curtype, $allowtypes))
				{
					$cur = round($avatar->size / 1024 / 1024, 2);
					if ($cur < 5)
					{
						$cur = $avatar->size;
						$randname = '' . rand() . time() . rand() . time() . $cur;
						$randname = md5($randname);
						$randfilenamename = "{$randname}.{$curtype}";
						$path = './web/MyImg/usersavatar/';
						$avatar->saveAs($path . $randfilenamename);
						if (Access::ChekIs($model->avatar))
						{
							if (is_file($path . $model->avatar))
							{
								@unlink($path . $model->avatar);
							}
						}
						$model->avatar = $randfilenamename;
					}
				}
			}
			$model->YouTube = strip_tags($model->YouTube);
			$model->Twitch = strip_tags($model->Twitch);
			$model->VK = strip_tags($model->VK);
			$model->Twitter = strip_tags($model->Twitter);
			$model->save();
			$this->redirect('/index.php?r=site/profile');
		}
		return $this->render('profile', ['model' => $model, 'upload' => $upload]);
	}
	public function actionAdmin()
	{
		if (!Access::IfUserRole('Admin'))
		{
			return $this->goHome();
		}
		return $this->render('admin');
	}
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;
use app\models\UserInfo;
use app\components\UsersFilesHTML;
use app\components\Access;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
		<link href="/web/css/MyStyle.css" rel="stylesheet"/>
	</head>
	<body>
		<?php $this->beginBody() ?>

		<div class="wrap">
			<?php
			$logo = '<img id="menulogoimg" src="/web/MyImg/goldensplit.png">';
			NavBar::begin([
				'brandLabel' => $logo,
				'brandUrl' => Yii::$app->homeUrl,
				'options' => [
					'class' => 'navbar-inverse navbar-fixed-top',
				],
			]);

			$items = [];
			$items[] = ['options' => ['class' => 'leftitems'], 'label' => 'Новости', 'url' => ['/site/index']];
			$items[] = ['options' => ['class' => 'leftitems'], 'label' => 'Игры', 'url' => ['/site/games']];
			$items[] = ['options' => ['class' => 'leftitems'], 'label' => 'Марафон', 'url' => ['/site/marathon']];
			if (Access::IfUserRole('Admin'))
			{
				$items[] = ['options' => ['class' => 'leftitems'], 'label' => 'Админка', 'url' => ['/site/admin']];
			}
			if (Yii::$app->user->isGuest)
			{
				$items[] = ['label' => 'Регистрация', 'options' => ['class' => 'logrefprof'], 'url' => ['/site/registration']];
				$items[] = ['label' => 'Вход',
					'options' => ['class' => 'logrefprof'],
					'linkOptions' => ['id' => 'loginbt'],
					'url' => ['/site/login']];
			}
			else
			{
				$items[] = ['label' => '<img src="/web/MyImg/logoutico.png"/>',
					'url' => ['/site/logout'],
					'options' => ['class' => 'leftbutonprof logoutico'],
					'linkOptions' => ['data-method' => 'post']];
				$id = Access::GetUserId();
				$userinfo = UserInfo::GetUserInfo($id);
				$src = UsersFilesHTML::GetSRC($userinfo->avatar);
				$name = Yii::$app->user->identity->username;
				$name .= "<img src='{$src}'/>";
				$items[] = ['label' => "Добро пожаловать, {$name}", 'url' => ['/site/profile'],
					'options' => ['class' => 'leftbutonprof profname'],
					'linkOptions' => ['id' => 'loginbt'],
				];
			}
			echo Nav::widget([
				'options' => ['class' => 'navbar-nav navbar-right'],
				'items' => $items,
				'encodeLabels' => false,
			]);
			NavBar::end();
			?>

			<div class="container">
				<?= $content ?>
			</div>

		</div>

		<footer class="footer">
			<div class="container">

			</div>
		</footer>

		<?php $this->endBody() ?>
	</body>
</html>
<?php $this->endPage() ?>